// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_omp_enabled
bool cpp_omp_enabled();
RcppExport SEXP _GMTM_cpp_omp_enabled() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_omp_enabled());
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmm
List cpp_gmm(arma::mat& data, int k, arma::mat means, int dist_type, int iter_km, int iter_em, bool verbose, int threads);
RcppExport SEXP _GMTM_cpp_gmm(SEXP dataSEXP, SEXP kSEXP, SEXP meansSEXP, SEXP dist_typeSEXP, SEXP iter_kmSEXP, SEXP iter_emSEXP, SEXP verboseSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type means(meansSEXP);
    Rcpp::traits::input_parameter< int >::type dist_type(dist_typeSEXP);
    Rcpp::traits::input_parameter< int >::type iter_km(iter_kmSEXP);
    Rcpp::traits::input_parameter< int >::type iter_em(iter_emSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmm(data, k, means, dist_type, iter_km, iter_em, verbose, threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kmeans
List cpp_kmeans(arma::mat& data, int k, arma::mat& means, int iter, bool verbose, int threads);
RcppExport SEXP _GMTM_cpp_kmeans(SEXP dataSEXP, SEXP kSEXP, SEXP meansSEXP, SEXP iterSEXP, SEXP verboseSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type means(meansSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kmeans(data, k, means, iter, verbose, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GMTM_cpp_omp_enabled", (DL_FUNC) &_GMTM_cpp_omp_enabled, 0},
    {"_GMTM_cpp_gmm", (DL_FUNC) &_GMTM_cpp_gmm, 8},
    {"_GMTM_cpp_kmeans", (DL_FUNC) &_GMTM_cpp_kmeans, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_GMTM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
