# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_gmm <- function(data, k, means, mode = 1L, iter_km = 10L, iter_em = 10L, verbose = FALSE) {
    .Call('_GMTM_cpp_gmm', PACKAGE = 'GMTM', data, k, means, mode, iter_km, iter_em, verbose)
}

cpp_kmeans <- function(data, k, means, iter = 10L, verbose = FALSE) {
    .Call('_GMTM_cpp_kmeans', PACKAGE = 'GMTM', data, k, means, iter, verbose)
}

